version: "3"
services:
  www:
    build: .
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.1
    links:
      - db:db
    ports:
      - 8081:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test